#!/usr/bin/env python3

import argparse
import subprocess

def main():
    parser = argparse.ArgumentParser(description='PRNG period analyzer')
    parser.add_argument("prog", help="program name", type=str)
    parser.add_argument("Nmax", help="range upper bound", type=int)

    args = parser.parse_args()
    filename = "/tmp/out"
    periods = []

    for i in range(args.Nmax):
        subprocess.call(["./"+args.prog, str(i), "128", "-o", filename])

        with open(filename, 'r') as infile :
            nums = [int(line.rstrip('\n')) for line in infile]
            track = [i]
            period = 1
            for num in nums:
                if num in track:
                    break
                else:
                    track.append(num)
                period = period + 1
            periods.append(period)

    import matplotlib.pyplot as plt

    plt.bar(range(args.Nmax), periods)
    plt.show()

if __name__ == "__main__":
    main()

