#!/usr/bin/env python3

import argparse
import subprocess
from collections import OrderedDict

def main():
    parser = argparse.ArgumentParser(description='PRNG distribution analyzer')
    parser.add_argument("prog", help="program name", type=str)
    parser.add_argument("Nmax", help="range upper bound", type=int)

    args = parser.parse_args()
    filename = "/tmp/out"
    di = {key: 0 for key in range(1000)}

    subprocess.call(["./"+args.prog, str(args.Nmax), "128", "-o", filename])

    with open(filename, 'r') as infile :
        nums = [int(line.rstrip('\n')) for line in infile]
        for num in nums:
            di[num] = di[num] + 1

    distribs = list(OrderedDict(sorted(di.items(), key=lambda t: t[0])).values())
    map(lambda v: v/1000, distribs)

    import matplotlib.pyplot as plt

    plt.bar(range(1000), distribs)
    plt.show()

if __name__ == "__main__":
    main()

